In [2]:
import numpy

In [3]:
numpy.__version__

'1.24.3'

In [4]:
import numpy as np

In [5]:
x=["2",2,2.0,True]
[type(item) for item in x]

[str, int, float, bool]

In [6]:
#int array
a=np.array([1,3,2,6,4,8])
a

array([1, 3, 2, 6, 4, 8])

In [7]:
a.dtype

dtype('int32')

In [8]:
np.random.seed(0)

x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

print("x3 dimension:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)


x3 dimension: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [9]:
x1


array([5, 0, 3, 3, 7, 9])

In [10]:
x1[5]


9

In [11]:
x1[-1]

9

In [12]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [13]:
print(x2[0,-3])
print(x2[-1,-3])

5
6


In [14]:
x1

array([5, 0, 3, 3, 7, 9])

In [15]:
x1[0:6:2]

array([5, 3, 7])

In [16]:
x1[::-1]

array([9, 7, 3, 3, 0, 5])

In [17]:
grid=np.arange(1,10)
print(grid)
grid=grid.reshape(3,3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
x=np.arange(1,4)
y=np.arange(4,7)
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [19]:
%timeit x=np.arange(9).reshape(3,3)
x
2**x

1.07 µs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


array([2, 4, 8], dtype=int32)

In [20]:
y=np.arange(1,10)
print(y)
y=y.reshape(3,3)
print(y)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
from scipy import special

In [22]:
import scipy.special as sp

In [23]:
y1=np.ones_like(y)
y1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])